apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-09-30T02:45:46Z"
  name: fcl-result-services
  #namespace: development
  resourceVersion: "45644897"
  uid: f959ce86-a9dc-45fb-abdb-6d03eeef2552
spec:
  clusterIP: 10.109.139.35
  clusterIPs:
  - 10.109.139.35
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5100
    protocol: TCP
    targetPort: 80
  selector:
    app: fcl-result-services
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
