apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-08-12T02:36:37Z"
  name: minio-service-ui
  #namespace: development
  resourceVersion: "86030960"
  uid: eb873eac-c4f0-4d85-8abb-00616040d7d4
spec:
  clusterIP: 10.111.197.97
  clusterIPs:
  - 10.111.197.97
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32328
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
