apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-08-08T09:11:13Z"
  name: rabbitmq
  #namespace: development
  resourceVersion: "57111418"
  uid: 14e2e4d3-29f0-4fc5-8ac4-f8dbb928a775
spec:
  clusterIP: 10.98.217.175
  clusterIPs:
  - 10.98.217.175
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: discovery
    nodePort: 30866
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: amqp
    nodePort: 32745
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
