apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: production
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXQubWFjZi5jby5pZDo1MDUwIjogewoJCQkiYXV0aCI6ICJjM2x6WVdSdGFXNDZjM2x6WVdSdGFXND0iCgkJfQoJfQp9