---
- name: Execute Command on Remote Hosts
  hosts: uat-worker
  tasks:
    - name: check docker version on worker node
      command: sudo docker --version
      register: command_output
      # Optionally, set 'become: true' if the command requires privilege escalation (sudo)
      #become: true
      become: true
      #become_user: 'sysadmin'

    - name: Display the output
      debug:
        var: command_output.stdout_lines
        #msg: "test value nama service: {{ SERVICENAME }} ,tag number: {{ TAGNUMBER }}"

    - name: Display the output from parsing value jenkins
      debug:
        #var: command_output.stdout_lines
        msg: "test value nama service: {{ SERVICENAME }} ,tag number: {{ TAGNUMBER }}"

