---
- name: Execute Command on Remote Hosts
  hosts: uat-worker
  tasks:
    - name: ping all worker node
      command: sudo docker images
      #command: java --version
      register: command_output
      # Optionally, set 'become: true' if the command requires privilege escalation (sudo)
      become: true

    - name: Display the output
      debug:
        var: command_output.stdout_lines

