apiVersion: v1
kind: ConfigMap
metadata:
  name: uat-mcf-config
  namespace: uat-mcf  # change if needed for mcf or maf environment
data:
  CONN_ACQUISITION: "uMvTxS/Jq1STP5pW5fw+qudSHRFkUh6CVEu4Og44FtNM0Tvwsdehyn4Ff+xu5rWUVYmcN0QVHrKHoZJII5Or0CbxfGOwgTXCnqh8qhR7D2/9tRnAcitmJtdIdhtIAfU3LAs+7pXZdrNWpuTbXC/v8gEOHUdl9+fvcW4J4aoE1PE/dyCVPwY2hCovFTSjEaRF31GsQ55t0gGtLy15Xrtu2BDF7VW7GtkaVBAZeEiBX2MtJNEw8j2ebLmRthQ54IeoGkoz911RfwD415fJ9pIoOsSbByrjuD6A"
  CONN_MASTER: "uMvTxS/Jq1QLIdsW2X65B4Pqr7LXVh1Vn5xHKGFotkEhLl1KYiDseIucR1Kn9wviNMOHuPvcachz+R2T8xGf/9GEdUz3FitQoicVO1f35Y9FH5i243ZnjrKFMl6bcUB56Dzh3dEC52RAtzJxSX1tImoFyyRdDFEmw0QOUh89/MqLF6Y31yxl77FmWVZsM2ASgyEjw/oS5ItYkAN+tyq4HuOb0y5zbo6NgL6J5fHj8Ey/TkGwDkULOFAi8cvIEVVPgNyJjMz+TgNrYom7vD1TB5CI2WH+5NNU"
  CONN_PAYMENT: "uMvTxS/Jq1STP5pW5fw+qudSHRFkUh6CVEu4Og44FtNM0TvwsdehyoH3BXUHem871cVaxFJjy4fBGggVeW46XWbDt+TVoIJw8BmoDCz436HrpTaRYVEVOg5sIS9oOIFJF4jBbCwzJeSkfRs4OA9vtW2E12gTT/CONe+5aK2+9bKcbxWBAwpcGeQOXrP5j88Vpwaq+46cW81zGzxqqCO+v8iqMIEltjWLIRll+OdU0G/Ros/hERJijmWVt7PUDMsKC+2keYHiKVI2C82OKL5jZHZXAppD59xsn1XhyTnbV6Y="
  CONN_TERMINATION: "uMvTxS/Jq1STP5pW5fw+qudSHRFkUh6CVEu4Og44FtNM0TvwsdehyncUU8hEWiQczggEqFnedFOaVsX/Xhl6IJU6k9xBBLdKorZySaoEsgtomw3WSmbsH7TgSYp4Unw9cTI4lP+YUg2OuiPKIO6LzepdmB/B+2n5Xhy93TsZAgHlfxWlL1pKxftejmRVgakzhXr8i0ceAzjhvIpKBYvUn3sbzi+ZpxnPSQBaFF3UwZI5jnxLl8O/7TCxAlK3nIJTYJ+K2P0O+WomqCJL7M7ewv23apGBHEHe"
  ASPNETCORE_ENVIRONMENT: "Development"
  COMPANY_ID_ENVIRONMENT: "3"
  COMPANY_NAME_ENVIRONMENT: "Mega Central Finance"
  ASPNETCORE_HTTP_PORT: "http://+:80"
  ASPNETCORE_URLS: "http://+80"
  JAEGER_EXPORT_LINK: "http://jaeger:4317"
  
