apiVersion: v1
kind: Service
metadata:
  name: fin-termination-services
  #namespace: uat-mcf
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: fin-termination-services
  type: ClusterIP
