apiVersion: v1
kind: Service
metadata:
  name: fin-vertel-services
  namespace: uat-mcf
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: fin-vertel-services
  type: ClusterIP
