apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXQubWNmLmNvLmlkIjp7InVzZXJuYW1lIjoia3ViZS1naXQiLCJwYXNzd29yZCI6Ik5keDM5cl9qaXRxRzd4eVZhN05XIiwiYXV0aCI6ImEzVmlaUzFuYVhRNlRtUjRNemx5WDJwcGRIRkhOM2g1Vm1FM1RsYz0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: test-gitlab
  namespace: development
type: kubernetes.io/dockerconfigjson
