apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-06-12T07:28:19Z"
  name: tempo
  #namespace: development
  resourceVersion: "151025057"
  uid: e1c57fbf-954b-4ab2-b1a2-27232c0b7b56
spec:
  clusterIP: 10.108.224.23
  clusterIPs:
  - 10.108.224.23
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30503
    port: 3200
    protocol: TCP
    targetPort: 3200
  - name: otlp-grpc
    nodePort: 30567
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    nodePort: 32402
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: tempo
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
