apiVersion: v1
kind: Service
metadata:
  name: acq-corporate-services
  #namespace: development
spec:
  ports:
  - port: 5088
    protocol: TCP
    targetPort: 80
  selector:
    app: acq-corporate-services
  type: ClusterIP
