apiVersion: v1
kind: Service
metadata:
  name: similarity-services
  #namespace: development
spec:
  ports:
  - port: 5099
    protocol: TCP
    targetPort: 5000
  selector:
    app: similarity-services
  type: ClusterIP
