apiVersion: v1
kind: Service
metadata:
  name: validate-services
  #namespace: development
spec:
  ports:
  - port: 5097
    protocol: TCP
    targetPort: 80
  selector:
    app: validate-services
  type: ClusterIP
