apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXQubWNmLmNvLmlkOjUwNTAiOnsidXNlcm5hbWUiOiJzeXNhZG1pbiIsInBhc3N3b3JkIjoic3lzYWRtaW4iLCJlbWFpbCI6ImFkaXRpby5wcmFib3dvQG1hZi5jby5pZCIsImF1dGgiOiJjM2x6WVdSdGFXNDZjM2x6WVdSdGFXND0ifX19
kind: Secret
metadata:
  name: cred-sysadmin
type: kubernetes.io/dockerconfigjson
