apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: acq-partner-services
  name: acq-partner-services
  #namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acq-partner-services
  template:
    metadata:
      labels:
        app: acq-partner-services
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: DOM_UPLOAD_MINIO
          value: http://minio-services.uat-moofi-mcf.svc.cluster.local:5095/api/Files/Upload
        - name: CONN_MASTER
          valueFrom:
            configMapKeyRef:
              key: CONN_MASTER
              name: moofi-cm
        - name: C_MOBILE
          valueFrom:
            configMapKeyRef:
              key: C_MOBILE
              name: moofi-cm
        - name: COMPANY_NAME_ALIAS
          value: mcf
        image: git.mcf.co.id:5050/moofi/acquisition.partner.services/acquisition.partner.services:3e247f9
        imagePullPolicy: IfNotPresent
        name: acq-partner-services
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
      imagePullSecrets:
      - name: cred-sysadmin
