apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: login-services
  name: login-services
  #namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-services
  template:
    metadata:
      labels:
        app: login-services
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: C_MOBILE
          valueFrom:
            configMapKeyRef:
              key: C_MOBILE
              name: moofi-cm
        - name: JWT_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: JWT_SECRET_KEY
              name: moofi-cm
        - name: JWT_TIME
          valueFrom:
            configMapKeyRef:
              key: JWT_TIME
              name: moofi-cm
        - name: JWT_HOUR
          valueFrom:
            configMapKeyRef:
              key: JWT_HOUR
              name: moofi-cm
        - name: DOM_LDAP
          valueFrom:
            configMapKeyRef:
              key: DOM_LDAP
              name: moofi-cm
        - name: COMPANY_NAME_ALIAS
          valueFrom:
            configMapKeyRef:
              key: COMPANY_NAME_ALIAS
              name: moofi-cm
        - name: C_Mongo
          value: 7iOd63L4kciN6Q6hCDOPfCyNghWoIDY7TMnbEiHXYXk1B6MqmrTNDUC4scPzPvj8gvrfQu//no6F87bbc/pTOkGONvoCoHVobwp8wABvRudG16ISjqL0e6nZSNCYXIAEmOeu0fv9TNw=
        - name: D_Mongo
          value: d8pMG0t+ga8Y6GyhUEVXag==
        image: git.mcf.co.id:5050/moofi/login.services/login.services:e5d0f3b
        imagePullPolicy: IfNotPresent
        name: login-services
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
      imagePullSecrets:
      - name: cred-sysadmin
