apiVersion: v1
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJnaXQubWNmLmNvLmlkOjUwNTAiOiB7CiAgICAgICAgICAgICJhdXRoIjogIk1qSXdNalF3TmpNeE9tcERValk0YzE5VmRIcHhRWGg1VVc4dFVtUmkiCiAgICAgICAgfQogICAgfQp9
kind: Secret
metadata:
  name: gitlab-mongo-job-secret
  namespace: prd-moofi-r2
type: kubernetes.io/dockerconfigjson
